language: java
sudo: false
dist: trusty
jdk:
- oraclejdk8
notifications:
  email: false
install:
#  ant jar_incl-libs
  maven
script:
- travis_wait java -cp dist/SBMLsqueezer-2.1.1/SBMLsqueezer_v2.1.1.jar:lib/junit-4.8.jar org.junit.runner.JUnitCore org.sbml.squeezer.test.cases.SBMLsqueezerTestSuite
