language: java
sudo: true
dist: trusty
jdk:
- oraclejdk8
notifications:
  email: false
#  ant jar_incl-libs
before_install:
  - sudo apt-get update
script:
#- travis_wait java -cp dist/SBMLsqueezer-2.1.1/SBMLsqueezer_v2.1.1.jar:lib/junit-4.8.jar org.junit.runner.JUnitCore org.sbml.squeezer.test.cases.SBMLsqueezerTestSuite
  - mvn clear compile package
