language: java
sudo: false
dist: trusty
jdk:
- oraclejdk8
notifications:
  email: false
script:
  - mvn "-Dtest=!UniUniKineticsTest#testMichMentRev+testPMRLWegRev, !BiBiKineticsTest#testPowerLawModularRateLawWegRev" clean compile package
  - mvn site
